Production:
  - name: "system-of-record"
    github: "https://github.com/LandRegistry/system-of-record"
    heroku: "lr-system-of-record"
    url: "lr-system-of-record.herokuapp.com/"
    port: 8000
    tech: [python, flask]
    dependencies: [postgres, redis]

  - name: "mint"
    github: "https://github.com/LandRegistry/mint"
    heroku: "lr-mint"
    url: "lr-mint.herokuapp.com/"
    port: 8001
    tech: [python, flask]
    dependencies: [system-of-record]

  - name: "casework-frontend"
    github: "https://github.com/LandRegistry/casework-frontend"
    heroku: "lr-casework-frontend"
    url: "casework.landregistryconcept.co.uk"
    port: 8004
    tech: [python, flask]
    dependencies: [mint]

  - name: "property-frontend"
    github: "https://github.com/LandRegistry/property-frontend"
    heroku: "lr-property-frontend"
    url: "www.gov.uk.landregistryconcept.co.uk"
    port: 8002
    tech: [python, flask]
    dependencies: [search-api]

  - name: "service-frontend"
    github: "https://github.com/LandRegistry/service-frontend"
    heroku: "lr-service-frontend"
    url: "lr-service-frontend.herokuapp.com"
    port: 8007
    tech: [python, flask]
    dependencies: [search-api]

  - name: "search-api"
    github: "https://github.com/LandRegistry/search-api"
    heroku: "lr-search-api"
    url: "lr-search-api.herokuapp.com"
    port: 8003
    tech: [python, flask]
    dependencies: [elastic-search]

  - name: "the-feeder"
    github: "https://github.com/LandRegistry/the-feeder"
    heroku: "lr-feeder-app"
    url: 
    port:
    tech: [python]
    dependencies: [redis]

Development:
  - name: "elastic-search-server"
    github: "https://github.com/LandRegistry/elastic-search-server"
    heroku: "n/a"
    url: "localhost:9200"
    port: 9200
    tech: [java]
    dependencies: []

  - name: "test-dashboard"
    github: "https://github.com/LandRegistry/test-dashboard"
    heroku: "lr-test-dashboard"
    url: "lr-test-dashboard.herokuapp.com"
    port: 7357
    tech: [python flask]
    dependencies: [travis]

  - name: "build-dashboard"
    github: "https://github.com/LandRegistry/build-dashboard"
    heroku: "lr-build-dashboard"
    url: "lr-build-dashboard.herokuapp.com"
    port: 8888
    tech: [python flask]
    dependencies: [travis]

  - name: "pull-dashboard"
    github: "https://github.com/LandRegistry/pull-dashboard"
    heroku: "lr-pull-dashboard"
    url: "lr-pull-dashboard.herokuapp.com"
    port: 8888
    tech: [python flask]
    dependencies: [github]

  - name: "team-dashboard"
    github: "https://github.com/LandRegistry/team-dashboard"
    heroku: "lr-team-dashboard"
    url: "team-dashboard.landregistryconcept.co.uk"
    port: 5000
    tech: [python flask]
    dependencies: []
